# Location of input files
mimic3_path: /data1/mimic/raw_csvs/
data_path: ./processed/

# Customize table headers
column_names:
    ID: ID
    t: t
    var_name: variable_name
    var_value: variable_value
